# Generated by Django 4.0.4 on 2022-05-07 14:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('organization', '__first__'),
    ]

    operations = [
        migrations.CreateModel(
            name='Job',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('job_name', models.CharField(blank=True, default='', max_length=150, null=True)),
                ('location_of_work', models.CharField(blank=True, default='', max_length=200, null=True)),
                ('job_type', models.CharField(blank=True, default='', max_length=9, null=True)),
                ('job_level', models.CharField(blank=True, default='', max_length=100, null=True)),
                ('site_url', models.CharField(default='', max_length=300, null=True)),
                ('onsite_remote', models.CharField(blank=True, default='Remote', max_length=200, null=True)),
                ('qualification', models.CharField(blank=True, default='', max_length=500, null=True)),
                ('job_description', models.TextField()),
                ('skills_required', models.TextField()),
                ('posted_on', models.DateTimeField(auto_now_add=True, null=True)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='organization.organization')),
            ],
        ),
    ]
