# Generated by Django 4.0.4 on 2022-05-07 07:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('job', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='job',
            name='created_on',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
