# Generated by Django 4.0 on 2022-05-07 13:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organization', '0002_alter_organization_company_desc_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='organization',
            name='company_desc',
            field=models.CharField(blank=True, default='', max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='organization',
            name='company_size',
            field=models.CharField(blank=True, default='', max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='organization',
            name='company_type',
            field=models.CharField(blank=True, default='', max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='organization',
            name='contact_no',
            field=models.CharField(blank=True, default='', max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='organization',
            name='industry',
            field=models.CharField(blank=True, default='', max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='organization',
            name='locations',
            field=models.CharField(blank=True, default='', max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='organization',
            name='org_name',
            field=models.CharField(blank=True, default='', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='organization',
            name='profile_pic',
            field=models.ImageField(blank=True, default='default_org_profile.jpeg', null=True, upload_to='org_profile_uploads/'),
        ),
        migrations.AlterField(
            model_name='organization',
            name='website_url',
            field=models.CharField(blank=True, default='', max_length=100, null=True),
        ),
    ]
