# Generated by Django 4.0.4 on 2022-05-07 15:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='aboutme',
            field=models.TextField(blank=True, max_length=15, null=True),
        ),
    ]
