# Generated by Django 4.0 on 2022-05-07 08:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='year_of_pass_out',
            field=models.IntegerField(blank=True, default=2000, null=True),
        ),
    ]
