# Generated by Django 4.0 on 2022-05-08 04:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0002_student_aboutme'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='year_of_pass_out',
            field=models.IntegerField(blank=True, default=2022, null=True),
        ),
    ]
